#!/data/data/com.termux/files/usr/bin/bash
dir=/data/data/com.termux/files
#colors
cyan='\033[1;36m'
green='\033[1;32m'
red='\033[1;31m'
yellow='\033[1;33m'
blue='\033[1;34m'
purple='\033[1;35m'
reset='\033[0m'

cd $dir/home
pkg install php
cd $dir/home
cd /sdcard
mkdir public_html
cd $dir/home/localhost
echo 
echo

chmod +x script
mv script $dir/usr/bin
clear
echo
echo
echo -e " $green     ======= Script Installed Succesfully======="

echo
echo
echo
cd $dir/home
rm -rf localhost
echo -e "$blue   You Can Run Script by Just call $red script"
sleep 3
echo
script
